language: node_js
services: docker

sudo: false

node_js:
  - "8.9"

install:
  - npm install

script:
  - ISLAND_LOGGER_LEVEL=crit npm run coverage

after_script:
  - npm i coveralls && cat ./coverage/lcov-remap.info | coveralls
  - npm i codeclimate-test-reporter && CODECLIMATE_REPO_TOKEN=9adc11da92bb65c25ddf5655c4d701855f0ccc4754be93dc4119a7d49f123cb4 codeclimate-test-reporter < ./coverage/lcov-remap.info

